package server

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"dnsmanager/internal/config"
	"dnsmanager/internal/revision"
)

type Server struct {
	cfg       config.Config
	layout    config.Layout
	startedAt time.Time
	revisions *revision.Service
}

type statusResponse struct {
	Service   string        `json:"service"`
	Version   string        `json:"version"`
	HTTPAddr  string        `json:"httpAddr"`
	StartedAt time.Time     `json:"startedAt"`
	Paths     config.Layout `json:"paths"`
}

func New(cfg config.Config) (*Server, error) {
	layout := cfg.Layout()
	if err := ensureLayout(layout); err != nil {
		return nil, err
	}

	revisions, err := revision.New(layout)
	if err != nil {
		return nil, err
	}

	return &Server{
		cfg:       cfg,
		layout:    layout,
		startedAt: time.Now().UTC(),
		revisions: revisions,
	}, nil
}

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("/healthz", s.handleHealthz)
	mux.HandleFunc("/api/v1/status", s.handleStatus)
	mux.HandleFunc("/api/v1/layout", s.handleLayout)
	mux.HandleFunc("/api/v1/config/revisions", s.handleRevisions)
	mux.HandleFunc("/api/v1/config/revisions/current", s.handleCurrentRevision)
	mux.HandleFunc("/api/v1/config/revisions/", s.handleRevisionAction)
	mux.Handle("/", s.uiHandler())

	return loggingMiddleware(mux)
}

func (s *Server) handleHealthz(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"status":    "ok",
		"service":   "dnsmanager",
		"timestamp": time.Now().UTC(),
	})
}

func (s *Server) handleStatus(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	writeJSON(w, http.StatusOK, statusResponse{
		Service:   "dnsmanager",
		Version:   s.cfg.Version,
		HTTPAddr:  s.cfg.HTTPAddr,
		StartedAt: s.startedAt,
		Paths:     s.layout,
	})
}

func (s *Server) handleLayout(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	writeJSON(w, http.StatusOK, s.layout)
}

func (s *Server) uiHandler() http.Handler {
	indexPath := filepath.Join(s.cfg.UIDistDir, "index.html")
	if _, err := os.Stat(indexPath); err == nil {
		distFS := os.DirFS(s.cfg.UIDistDir)
		return spaFileServer(distFS)
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprint(w, fallbackHTML())
	})
}

func ensureLayout(layout config.Layout) error {
	paths := []string{
		layout.DataDir,
		layout.ConfigDir,
		layout.ContentDir,
		layout.ManagedDir,
		layout.ManualDir,
		layout.GeneratedDir,
		layout.BackupsDir,
		layout.StagingDir,
		layout.AppliedDir,
	}

	for _, path := range paths {
		if err := os.MkdirAll(path, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", path, err)
		}
	}

	placeholder := layout.ActiveGeneratedFile
	if _, err := os.Stat(placeholder); err != nil {
		content := "# Generated by dnsmanager foundation scaffold.\n# Future milestones will render managed dnsmasq fragments here.\n"
		if writeErr := os.WriteFile(placeholder, []byte(content), 0o644); writeErr != nil {
			return fmt.Errorf("write placeholder config: %w", writeErr)
		}
	}

	return nil
}

func (s *Server) handleRevisions(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		revisions, err := s.revisions.List(r.Context())
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"revisions": revisions})
	case http.MethodPost:
		var input revision.CreateInput
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			http.Error(w, "invalid json body", http.StatusBadRequest)
			return
		}

		created, err := s.revisions.CreateDraft(r.Context(), input)
		if err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		writeJSON(w, http.StatusCreated, created)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (s *Server) handleCurrentRevision(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	current, err := s.revisions.Current(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusOK, current)
}

func (s *Server) handleRevisionAction(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/api/v1/config/revisions/")
	path = strings.Trim(path, "/")
	if path == "" {
		http.NotFound(w, r)
		return
	}

	parts := strings.Split(path, "/")
	revisionID, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		http.Error(w, "invalid revision id", http.StatusBadRequest)
		return
	}

	if len(parts) == 1 {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		revision, getErr := s.revisions.Get(r.Context(), revisionID)
		if getErr != nil {
			status := http.StatusInternalServerError
			if errors.Is(getErr, sql.ErrNoRows) || errors.Is(getErr, os.ErrNotExist) {
				status = http.StatusNotFound
			}
			http.Error(w, getErr.Error(), status)
			return
		}
		writeJSON(w, http.StatusOK, revision)
		return
	}

	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var revisionState revision.Revision
	switch parts[1] {
	case "validate":
		revisionState, err = s.revisions.Validate(r.Context(), revisionID)
	case "apply":
		revisionState, err = s.revisions.Apply(r.Context(), revisionID)
	case "rollback":
		revisionState, err = s.revisions.Rollback(r.Context(), revisionID)
	default:
		http.NotFound(w, r)
		return
	}

	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	writeJSON(w, http.StatusOK, revisionState)
}

func fallbackHTML() string {
	return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>dnsmanager</title>
    <style>
      :root {
        color-scheme: light;
        font-family: "IBM Plex Sans", "Avenir Next", "Segoe UI Variable", sans-serif;
        background: #f6f3eb;
        color: #1f2d25;
      }
      body {
        margin: 0;
        min-height: 100vh;
        display: grid;
        place-items: center;
        background:
          radial-gradient(circle at top left, rgba(77, 140, 87, 0.18), transparent 30rem),
          linear-gradient(160deg, #f7f3e9 0%, #ede6d8 100%);
      }
      main {
        width: min(42rem, calc(100vw - 2rem));
        padding: 2rem;
        border-radius: 1.5rem;
        background: rgba(255, 252, 247, 0.9);
        box-shadow: 0 1.5rem 4rem rgba(43, 61, 49, 0.12);
      }
      h1 { margin-top: 0; font-size: clamp(2rem, 6vw, 3rem); }
      p { line-height: 1.6; }
      code {
        padding: 0.15rem 0.4rem;
        border-radius: 0.35rem;
        background: rgba(60, 97, 74, 0.12);
      }
      a { color: #20593a; }
    </style>
  </head>
  <body>
    <main>
      <h1>dnsmanager foundation is running</h1>
      <p>The backend is healthy, the shared volume layout has been created, and the Svelte UI can be built into <code>web/dist</code> when frontend dependencies are installed.</p>
      <p>Check <a href="/api/v1/status">/api/v1/status</a> for the current runtime layout.</p>
    </main>
  </body>
</html>`
}

func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)

	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(payload)
}

func spaFileServer(root fs.FS) http.Handler {
	fileServer := http.FileServerFS(root)

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" {
			r.URL.Path = "/index.html"
			fileServer.ServeHTTP(w, r)
			return
		}

		if _, err := fs.Stat(root, r.URL.Path[1:]); err == nil {
			fileServer.ServeHTTP(w, r)
			return
		}

		r.URL.Path = "/index.html"
		fileServer.ServeHTTP(w, r)
	})
}

func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		fmt.Printf("%s %s %s\n", r.Method, r.URL.Path, time.Since(start))
	})
}
